// HTML Code partly generated by an LLM

package com.MdgCorp.RestWebService.controller;

import com.MdgCorp.RestWebService.entity.Car;
import com.MdgCorp.RestWebService.service.CarService;
import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.*;

import java.util.Objects;

@RestController
public class CarListController {

    private final CarService carService;

    public CarListController(CarService carService) {
        this.carService = carService;
    }

    @GetMapping("/view/cars")
    @ResponseStatus(HttpStatus.OK)
    public String ViewListOfCars() {

        StringBuilder html = new StringBuilder();

        html.append("<html>")
                .append("<head>")
                .append("<meta charset='UTF-8'>")
                .append("<meta name='viewport' content='width=device-width, initial-scale=1.0'>")
                .append("<title>Cars - MDG Corp</title>")
                .append("<style>")
                .append("body {")
                .append("font-family: Arial, sans-serif;")
                .append("background: #f4f6f8;")
                .append("margin: 0;")
                .append("color: #1f2937;")
                .append("}")
                .append(".container {")
                .append("max-width: 900px;")
                .append("margin: 0 auto;")
                .append("padding: 40px 20px;")
                .append("}")
                .append(".back {")
                .append("display: inline-block;")
                .append("margin-bottom: 25px;")
                .append("color: #2563eb;")
                .append("text-decoration: none;")
                .append("font-weight: bold;")
                .append("}")
                .append(".back:hover {")
                .append("text-decoration: underline;")
                .append("}")
                .append("h1 {")
                .append("text-align: center;")
                .append("margin-bottom: 35px;")
                .append("}")
                .append(".list {")
                .append("display: grid;")
                .append("grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));")
                .append("gap: 20px;")
                .append("list-style: none;")
                .append("padding: 0;")
                .append("}")
                .append(".card {")
                .append("background: white;")
                .append("border-radius: 12px;")
                .append("padding: 25px;")
                .append("box-shadow: 0 4px 12px rgba(0,0,0,0.08);")
                .append("transition: transform 0.2s, box-shadow 0.2s;")
                .append("}")
                .append(".card:hover {")
                .append("transform: translateY(-4px);")
                .append("box-shadow: 0 8px 20px rgba(0,0,0,0.12);")
                .append("}")
                .append(".card a {")
                .append("color: #111827;")
                .append("text-decoration: none;")
                .append("font-size: 20px;")
                .append("font-weight: bold;")
                .append("}")
                .append(".card a:hover {")
                .append("color: #2563eb;")
                .append("}")
                .append("</style>")
                .append("</head>")
                .append("<body>")
                .append("<div class='container'>")
                .append("<a class='back' href='/'>← Back</a>")
                .append("<h1>🚗 List of Cars</h1>")
                .append("<ul class='list'>");

        for (Car car : carService.getCars()) {
            html.append("<li class='card'>")
                    .append("<a href='/view/cars/")
                    .append(car.getPlateNumber())
                    .append("'>")
                    .append(car.getPlateNumber())
                    .append("</a>")
                    .append("</li>");
        }

        html.append("</ul>")
                .append("</div>")
                .append("</body>")
                .append("</html>");

        return html.toString();
    }

    @GetMapping("/view/cars/{plateNumber}")
    @ResponseStatus(HttpStatus.OK)
    public String Print(@PathVariable("plateNumber") String plateNumber) throws Exception {

        for (Car car : carService.getCars()) {
            if (Objects.equals(car.getPlateNumber(), plateNumber)) {

                String rentStatus = car.isRent()
                        ? "<span class='badge available'>AVAILABLE</span>"
                        : "<span class='badge rented'>RENTED</span>";

                return "<html>" +
                        "<head>" +
                        "<meta charset='UTF-8'>" +
                        "<meta name='viewport' content='width=device-width, initial-scale=1.0'>" +
                        "<title>Car " + car.getPlateNumber() + "</title>" +
                        "<style>" +
                        "body {" +
                        "font-family: Arial, sans-serif;" +
                        "background: #f4f6f8;" +
                        "margin: 0;" +
                        "color: #1f2937;" +
                        "}" +
                        ".container {" +
                        "max-width: 700px;" +
                        "margin: 0 auto;" +
                        "padding: 40px 20px;" +
                        "}" +
                        ".back {" +
                        "display: inline-block;" +
                        "margin-bottom: 25px;" +
                        "color: #2563eb;" +
                        "text-decoration: none;" +
                        "font-weight: bold;" +
                        "}" +
                        ".box {" +
                        "background: white;" +
                        "border-radius: 16px;" +
                        "padding: 35px;" +
                        "box-shadow: 0 5px 20px rgba(0,0,0,0.08);" +
                        "}" +
                        "h1 {" +
                        "margin-top: 0;" +
                        "margin-bottom: 30px;" +
                        "}" +
                        ".info {" +
                        "display: flex;" +
                        "justify-content: space-between;" +
                        "padding: 15px 0;" +
                        "border-bottom: 1px solid #e5e7eb;" +
                        "}" +
                        ".label {" +
                        "font-weight: bold;" +
                        "color: #6b7280;" +
                        "}" +
                        ".badge {" +
                        "display: inline-block;" +
                        "padding: 6px 12px;" +
                        "border-radius: 20px;" +
                        "font-size: 13px;" +
                        "font-weight: bold;" +
                        "}" +
                        ".rented {" +
                        "background: #fee2e2;" +
                        "color: #b91c1c;" +
                        "}" +
                        ".available {" +
                        "background: #dcfce7;" +
                        "color: #15803d;" +
                        "}" +
                        "</style>" +
                        "</head>" +
                        "<body>" +
                        "<div class='container'>" +
                        "<a class='back' href='/view/cars'>← Back to cars</a>" +
                        "<div class='box'>" +
                        "<h1>🚗 " + car.getPlateNumber() + "</h1>" +
                        "<div class='info'><span class='label'>Plate number</span><span>" + car.getPlateNumber() + "</span></div>" +
                        "<div class='info'><span class='label'>Brand</span><span>" + car.getBrand() + "</span></div>" +
                        "<div class='info'><span class='label'>Price</span><span>" + String.format("%.2f €", car.getPrice()) + "</span></div>" +
                        "<div class='info'><span class='label'>Status</span><span>" + rentStatus + "</span></div>" +
                        "</div>" +
                        "</div>" +
                        "</body>" +
                        "</html>";
            }
        }

        return "";
    }

    @PutMapping("/cars/{plateNumber}")
    @ResponseStatus(HttpStatus.OK)
    public void rentOrGetBack(
            @PathVariable("plateNumber") String plateNumber,
            @RequestParam(value = "rent", required = true) boolean rent
    ) throws Exception {

        for (Car car : carService.getCars()) {
            if (Objects.equals(car.getPlateNumber(), plateNumber)) {
                car.toggleRent();
            }
        }
    }
}