// HTML Code partly generated by an LLM

package com.MdgCorp.RestWebService.controller;

import com.MdgCorp.RestWebService.entity.Contract;
import com.MdgCorp.RestWebService.service.ContractService;
import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.*;

import java.util.Objects;

@RestController
public class ContractListController {

    private final ContractService contractService;

    public ContractListController(ContractService contractService) {
        this.contractService = contractService;
    }

    @GetMapping("/view/contracts")
    @ResponseStatus(HttpStatus.OK)
    public String ViewListOfContracts() {

        StringBuilder html = new StringBuilder();

        html.append("<html>")
                .append("<head>")
                .append("<meta charset='UTF-8'>")
                .append("<meta name='viewport' content='width=device-width, initial-scale=1.0'>")
                .append("<title>Contracts - MDG Corp</title>")
                .append("<style>")
                .append("body {")
                .append("font-family: Arial, sans-serif;")
                .append("background: #f4f6f8;")
                .append("margin: 0;")
                .append("color: #1f2937;")
                .append("}")
                .append(".container {")
                .append("max-width: 900px;")
                .append("margin: 0 auto;")
                .append("padding: 40px 20px;")
                .append("}")
                .append(".back {")
                .append("display: inline-block;")
                .append("margin-bottom: 25px;")
                .append("color: #2563eb;")
                .append("text-decoration: none;")
                .append("font-weight: bold;")
                .append("}")
                .append("h1 {")
                .append("text-align: center;")
                .append("margin-bottom: 35px;")
                .append("}")
                .append(".list {")
                .append("display: grid;")
                .append("grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));")
                .append("gap: 20px;")
                .append("list-style: none;")
                .append("padding: 0;")
                .append("}")
                .append(".card {")
                .append("background: white;")
                .append("border-radius: 12px;")
                .append("padding: 25px;")
                .append("box-shadow: 0 4px 12px rgba(0,0,0,0.08);")
                .append("transition: transform 0.2s, box-shadow 0.2s;")
                .append("}")
                .append(".card:hover {")
                .append("transform: translateY(-4px);")
                .append("box-shadow: 0 8px 20px rgba(0,0,0,0.12);")
                .append("}")
                .append(".card a {")
                .append("color: #111827;")
                .append("text-decoration: none;")
                .append("font-size: 20px;")
                .append("font-weight: bold;")
                .append("}")
                .append(".card a:hover {")
                .append("color: #2563eb;")
                .append("}")
                .append("</style>")
                .append("</head>")
                .append("<body>")
                .append("<div class='container'>")
                .append("<a class='back' href='/'>← Back</a>")
                .append("<h1>📄 List of Contracts</h1>")
                .append("<ul class='list'>");

        for (Contract contract : contractService.getContracts()) {
            html.append("<li class='card'>")
                    .append("<a href='/view/contracts/")
                    .append(contract.getId())
                    .append("'>")
                    .append("Contract #")
                    .append(contract.getId())
                    .append("</a>")
                    .append("</li>");
        }

        html.append("</ul>")
                .append("</div>")
                .append("</body>")
                .append("</html>");

        return html.toString();
    }

    @GetMapping("/view/contracts/{id}")
    @ResponseStatus(HttpStatus.OK)
    public String Print(@PathVariable("id") Long id) throws Exception {

        Contract contractFound = new Contract();

        for (Contract contract : contractService.getContracts()) {
            if (Objects.equals(contract.getId(), id)) {
                contractFound = contract;
            }
        }

        String endDate = contractFound.getEndDate() == null
                ? "<span class='badge active'>ACTIVE</span>"
                : contractFound.getEndDate().toString();

        return "<html>" +
                "<head>" +
                "<meta charset='UTF-8'>" +
                "<meta name='viewport' content='width=device-width, initial-scale=1.0'>" +
                "<title>Contract " + contractFound.getId() + " - MDG Corp</title>" +
                "<style>" +
                "body {" +
                "font-family: Arial, sans-serif;" +
                "background: #f4f6f8;" +
                "margin: 0;" +
                "color: #1f2937;" +
                "}" +
                ".container {" +
                "max-width: 700px;" +
                "margin: 0 auto;" +
                "padding: 40px 20px;" +
                "}" +
                ".back {" +
                "display: inline-block;" +
                "margin-bottom: 25px;" +
                "color: #2563eb;" +
                "text-decoration: none;" +
                "font-weight: bold;" +
                "}" +
                ".box {" +
                "background: white;" +
                "border-radius: 16px;" +
                "padding: 35px;" +
                "box-shadow: 0 5px 20px rgba(0,0,0,0.08);" +
                "}" +
                "h1 {" +
                "margin-top: 0;" +
                "margin-bottom: 30px;" +
                "}" +
                ".info {" +
                "display: flex;" +
                "justify-content: space-between;" +
                "gap: 20px;" +
                "padding: 16px 0;" +
                "border-bottom: 1px solid #e5e7eb;" +
                "}" +
                ".label {" +
                "font-weight: bold;" +
                "color: #6b7280;" +
                "}" +
                ".badge {" +
                "display: inline-block;" +
                "padding: 6px 12px;" +
                "border-radius: 20px;" +
                "font-size: 13px;" +
                "font-weight: bold;" +
                "background: #dcfce7;" +
                "color: #15803d;" +
                "}" +
                "</style>" +
                "</head>" +
                "<body>" +
                "<div class='container'>" +
                "<a class='back' href='/view/contracts'>← Back to contracts</a>" +
                "<div class='box'>" +
                "<h1>📄 Contract #" + contractFound.getId() + "</h1>" +
                "<div class='info'><span class='label'>Person</span><span>" + contractFound.getPerson().getName() + "</span></div>" +
                "<div class='info'><span class='label'>Car</span><span>" + contractFound.getCar().getPlateNumber() + "</span></div>" +
                "<div class='info'><span class='label'>Start date</span><span>" + contractFound.getStartDate() + "</span></div>" +
                "<div class='info'><span class='label'>End date</span><span>" + endDate + "</span></div>" +
                "</div>" +
                "</div>" +
                "</body>" +
                "</html>";
    }
}