// HTML Code partly generated by an LLM

package com.MdgCorp.RestWebService.controller;

import com.MdgCorp.RestWebService.entity.Car;
import com.MdgCorp.RestWebService.entity.Contract;
import com.MdgCorp.RestWebService.entity.Person;
import com.MdgCorp.RestWebService.service.CarService;
import com.MdgCorp.RestWebService.service.ContractService;
import com.MdgCorp.RestWebService.service.PersonService;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;
import jakarta.annotation.PostConstruct;

import java.time.LocalDate;
import java.util.List;
import java.util.Random;

@RestController
public class MainPage {

    private final CarService carService;
    private final PersonService personService;
    private final ContractService contractService;

    public MainPage(
            CarService carService,
            PersonService personService,
            ContractService contractService
    ) {
        this.carService = carService;
        this.personService = personService;
        this.contractService = contractService;
    }

    public void initializeCars() {
        Random random = new Random();

        String[] brands = {
                "Toyota",
                "BMW",
                "Mercedes",
                "Audi",
                "Renault",
                "Peugeot",
                "Citroen",
                "Ford",
                "Tesla",
                "Volkswagen"
        };

        for (int i = 0; i < 10; i++) {
            String brand = brands[random.nextInt(brands.length)];
            String characters = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
            String numbers = "0123456789";

            StringBuilder plateNumber = new StringBuilder();

            for (int j = 0; j < 2; j++) {
                plateNumber.append(
                        characters.charAt(random.nextInt(characters.length()))
                );
            }

            plateNumber.append("-");

            for (int j = 0; j < 3; j++) {
                plateNumber.append(
                        numbers.charAt(random.nextInt(numbers.length()))
                );
            }

            plateNumber.append("-");

            for (int j = 0; j < 2; j++) {
                plateNumber.append(
                        characters.charAt(random.nextInt(characters.length()))
                );
            }

            double price = 10 + (90 * random.nextDouble());

            carService.addCar(
                    new Car(plateNumber.toString(), brand, price)
            );
        }
    }

    public void initializePersons() {
        Random random = new Random();

        String[] names = {
                "Zaif",
                "Roland",
                "Marc",
                "Joseph",
                "Jacques",
                "Elise",
                "Clara",
                "Marin",
                "Jeanne",
                "Mathieu"
        };

        for (int i = 0; i < 10; i++) {
            personService.addPerson(
                    new Person(names[i])
            );
        }
    }

    public void initializeContracts() {

        Random random = new Random();

        List<Person> persons = personService.getPersons();
        List<Car> cars = carService.getCars();

        for (int i = 0; i < 5; i++) {

            Person person = persons.get(random.nextInt(persons.size()));
            Car car = cars.get(random.nextInt(cars.size()));

            LocalDate startDate = LocalDate.now()
                    .minusDays(30 + random.nextInt(151));

            LocalDate endDate;

            if (random.nextInt(100) < 40) {
                endDate = null;
            } else {
                endDate = startDate.plusDays(1 + random.nextInt(30));
            }

            contractService.addContract(
                    new Contract(person, car, startDate, endDate)
            );
        }
    }

    @PostConstruct
    public void initializeData() {
        initializeCars();
        initializePersons();
        initializeContracts();
    }

    @GetMapping("/")
    public String hello() {

        return "<html>" +
                "<head>" +
                "<meta charset='UTF-8'>" +
                "<meta name='viewport' content='width=device-width, initial-scale=1.0'>" +
                "<title>MDG Corp - Rent Service</title>" +
                "<style>" +
                "body {" +
                "font-family: Arial, sans-serif;" +
                "background: #f4f6f8;" +
                "margin: 0;" +
                "min-height: 100vh;" +
                "display: flex;" +
                "align-items: center;" +
                "justify-content: center;" +
                "color: black;" +
                "}" +
                ".container {" +
                "width: 90%;" +
                "max-width: 800px;" +
                "text-align: center;" +
                "}" +
                "h1 {" +
                "font-size: 42px;" +
                "margin-bottom: 10px;" +
                "}" +
                ".subtitle {" +
                "color: #d1d5db;" +
                "font-size: 18px;" +
                "margin-bottom: 40px;" +
                "}" +
                ".buttons {" +
                "display: grid;" +
                "grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));" +
                "gap: 20px;" +
                "}" +
                ".button {" +
                "display: block;" +
                "padding: 25px 20px;" +
                "background: white;" +
                "color: #111827;" +
                "border-radius: 14px;" +
                "text-decoration: none;" +
                "font-size: 20px;" +
                "font-weight: bold;" +
                "box-shadow: 0 8px 20px rgba(0,0,0,0.2);" +
                "transition: transform 0.2s, box-shadow 0.2s;" +
                "}" +
                ".button:hover {" +
                "transform: translateY(-5px);" +
                "box-shadow: 0 14px 28px rgba(0,0,0,0.3);" +
                "}" +
                ".icon {" +
                "display: block;" +
                "font-size: 35px;" +
                "margin-bottom: 10px;" +
                "}" +
                "</style>" +
                "</head>" +
                "<body>" +
                "<div class='container'>" +
                "<h1>MDG Corp</h1>" +
                "<div class='subtitle'>Car Rental Management Service</div>" +
                "<div class='buttons'>" +
                "<a class='button' href='/view/cars'>" +
                "<span class='icon'>🚗</span>" +
                "Cars" +
                "</a>" +
                "<a class='button' href='/view/persons'>" +
                "<span class='icon'>👤</span>" +
                "Persons" +
                "</a>" +
                "<a class='button' href='/view/contracts'>" +
                "<span class='icon'>📄</span>" +
                "Contracts" +
                "</a>" +
                "</div>" +
                "</div>" +
                "</body>" +
                "</html>";
    }
}