// HTML Code partly generated by an LLM

package com.MdgCorp.RestWebService.controller;

import com.MdgCorp.RestWebService.entity.Person;
import com.MdgCorp.RestWebService.service.PersonService;
import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.*;

import java.util.Objects;

@RestController
public class PersonListController {

    private final PersonService personService;

    public PersonListController(PersonService personService) {
        this.personService = personService;
    }

    @GetMapping("/view/persons")
    @ResponseStatus(HttpStatus.OK)
    public String ViewListOfPersons() {

        StringBuilder html = new StringBuilder();

        html.append("<html>")
                .append("<head>")
                .append("<meta charset='UTF-8'>")
                .append("<meta name='viewport' content='width=device-width, initial-scale=1.0'>")
                .append("<title>Persons - MDG Corp</title>")
                .append("<style>")
                .append("body {")
                .append("font-family: Arial, sans-serif;")
                .append("background: #f4f6f8;")
                .append("margin: 0;")
                .append("color: #1f2937;")
                .append("}")
                .append(".container {")
                .append("max-width: 900px;")
                .append("margin: 0 auto;")
                .append("padding: 40px 20px;")
                .append("}")
                .append(".back {")
                .append("display: inline-block;")
                .append("margin-bottom: 25px;")
                .append("color: #2563eb;")
                .append("text-decoration: none;")
                .append("font-weight: bold;")
                .append("}")
                .append("h1 {")
                .append("text-align: center;")
                .append("margin-bottom: 35px;")
                .append("}")
                .append(".list {")
                .append("display: grid;")
                .append("grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));")
                .append("gap: 20px;")
                .append("list-style: none;")
                .append("padding: 0;")
                .append("}")
                .append(".card {")
                .append("background: white;")
                .append("border-radius: 12px;")
                .append("padding: 25px;")
                .append("box-shadow: 0 4px 12px rgba(0,0,0,0.08);")
                .append("transition: transform 0.2s, box-shadow 0.2s;")
                .append("}")
                .append(".card:hover {")
                .append("transform: translateY(-4px);")
                .append("box-shadow: 0 8px 20px rgba(0,0,0,0.12);")
                .append("}")
                .append(".card a {")
                .append("color: #111827;")
                .append("text-decoration: none;")
                .append("font-size: 20px;")
                .append("font-weight: bold;")
                .append("}")
                .append(".card a:hover {")
                .append("color: #2563eb;")
                .append("}")
                .append("</style>")
                .append("</head>")
                .append("<body>")
                .append("<div class='container'>")
                .append("<a class='back' href='/'>← Back</a>")
                .append("<h1>👤 List of Persons</h1>")
                .append("<ul class='list'>");

        for (Person person : personService.getPersons()) {
            html.append("<li class='card'>")
                    .append("<a href='/view/persons/")
                    .append(person.getName())
                    .append("'>")
                    .append(person.getName())
                    .append("</a>")
                    .append("</li>");
        }

        html.append("</ul>")
                .append("</div>")
                .append("</body>")
                .append("</html>");

        return html.toString();
    }

    @GetMapping("/view/persons/{name}")
    @ResponseStatus(HttpStatus.OK)
    public String Print(@PathVariable("name") String name) throws Exception {

        Person P = new Person();

        for (Person person : personService.getPersons()) {
            if (Objects.equals(person.getName(), name)) {
                P = person;
            }
        }

        return "<html>" +
                "<head>" +
                "<meta charset='UTF-8'>" +
                "<meta name='viewport' content='width=device-width, initial-scale=1.0'>" +
                "<title>" + P.getName() + " - MDG Corp</title>" +
                "<style>" +
                "body {" +
                "font-family: Arial, sans-serif;" +
                "background: #f4f6f8;" +
                "margin: 0;" +
                "color: #1f2937;" +
                "}" +
                ".container {" +
                "max-width: 700px;" +
                "margin: 0 auto;" +
                "padding: 40px 20px;" +
                "}" +
                ".back {" +
                "display: inline-block;" +
                "margin-bottom: 25px;" +
                "color: #2563eb;" +
                "text-decoration: none;" +
                "font-weight: bold;" +
                "}" +
                ".box {" +
                "background: white;" +
                "border-radius: 16px;" +
                "padding: 35px;" +
                "box-shadow: 0 5px 20px rgba(0,0,0,0.08);" +
                "}" +
                "h1 {" +
                "margin-top: 0;" +
                "}" +
                ".info {" +
                "padding: 15px 0;" +
                "border-bottom: 1px solid #e5e7eb;" +
                "}" +
                ".label {" +
                "font-weight: bold;" +
                "color: #6b7280;" +
                "margin-right: 10px;" +
                "}" +
                "</style>" +
                "</head>" +
                "<body>" +
                "<div class='container'>" +
                "<a class='back' href='/view/persons'>← Back to persons</a>" +
                "<div class='box'>" +
                "<h1>👤 " + P.getName() + "</h1>" +
                "<div class='info'><span class='label'>Name:</span>" + P.getName() + "</div>" +
                "</div>" +
                "</div>" +
                "</body>" +
                "</html>";
    }
}